# Generated by Django 2.2.3 on 2023-07-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmallParentingAPI', '0002_auto_20230717_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hijo',
            old_name='Asignatura_Favorita',
            new_name='asignatura_favorita',
        ),
        migrations.RenameField(
            model_name='hijo',
            old_name='Enfermedad_diagnosticada',
            new_name='enfermedad_diagnosticada',
        ),
    ]
