# Generated by Django 2.2.3 on 2023-07-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmallParentingAPI', '0003_auto_20230717_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hijo',
            old_name='asignatura_favorita',
            new_name='materia_favorita',
        ),
    ]
