# Generated by Django 2.2.3 on 2023-07-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallParentingAPI', '0005_auto_20230717_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='respuesta_api',
            field=models.TextField(blank=True, null=True),
        ),
    ]
