# Generated by Django 2.2.3 on 2023-07-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallParentingAPI', '0006_hijo_respuesta_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='conversacion_personalizada',
            field=models.TextField(default='[]'),
        ),
    ]
